name: Teste

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: teste
    steps:
    - name: Grant execute permission for gradlew
      env:
        TESTE: ${{ secrets.TESTE }}
      run: echo $TESTE